# coding=utf-8

#    National Oceanic and Atmospheric Administration
#    Alaskan Fisheries Science Center
#    Resource Assessment and Conservation Engineering
#    Midwater Assessment and Conservation Engineering

# THIS SOFTWARE AND ITS DOCUMENTATION ARE CONSIDERED TO BE IN THE PUBLIC DOMAIN
# AND THUS ARE AVAILABLE FOR UNRESTRICTED PUBLIC USE. THEY ARE FURNISHED "AS
# IS." THE AUTHORS, THE UNITED STATES GOVERNMENT, ITS INSTRUMENTALITIES,
# OFFICERS, EMPLOYEES, AND AGENTS MAKE NO WARRANTY, EXPRESS OR IMPLIED, AS TO
# THE USEFULNESS OF THE SOFTWARE AND DOCUMENTATION FOR ANY PURPOSE.  THEY
# ASSUME NO RESPONSIBILITY (1) FOR THE USE OF THE SOFTWARE AND DOCUMENTATION;
# OR (2) TO PROVIDE TECHNICAL SUPPORT TO USERS.

'''
.. module:: echolab2.instruments.echosounder

    :synopsis:  The top level interface for reading data files collected
                using scientific echosounders commonly used in fisheries
                stock assessment and research.

    The echosounder module provides a simplified interface for reading raw data
    generated by EK60, EK80, and similar instruments. Due to the wide variety of
    instruments that utilize the Simrad "raw" data format and their many configuration
    options, pyEcholab's classes for working with these data are complex. The
    echosounder module makes a few assumptions that are applicable to most use
    cases that significantly reduces this complexity. These assumptions are:

        All raw files passed to the read() function will have the same general
        file format (EK60 or EK80). If you pass a list of multiple files to
        read() where some are EK60 formatted and some are EK80, an error will
        be raised.

        All files passed to the read() function will contain the same data type.
        The data types are power only, angles only, power+angles, and complex.
        Mixing types will not result in an error, but only one type of data
        will be returned.

    If you need to read different formats, or different data types you can read
    them separately and combine after they have been read and converted, or you
    can implement something more complex using the EK60 and/or EK80 objects
    directly.

| Developed by:  Rick Towler   <rick.towler@noaa.gov>
| National Oceanic and Atmospheric Administration (NOAA)
| Alaska Fisheries Science Center (AFSC)
| Midwater Assesment and Conservation Engineering Group (MACE)
|
| Authors:
|       Rick Towler   <rick.towler@noaa.gov>
| Maintained by:
|       Rick Towler   <rick.towler@noaa.gov>

$Id$
'''

import os
import copy
import warnings
import numpy as np
from . import EK80
from . import EK60
from .util.simrad_raw_file import RawSimradFile, SimradEOF
from .util import simrad_utils
from ..processing import mask, noise, line


SIMRAD_EK60 = 0
SIMRAD_EK80 = 1

def read(files, ignore_errors=False, **kwargs):
    """read reads one or more Simrad EK60 style *OR* EK80 style .raw data files
    and returns a EK60 or EK80 object containing the data. Supported systems are:

        Simrad EK60, ES60, ME70, ES70, EK80, ES80

    The simplified interface provided by the echosounder module assumes that
    all files will have the same format (EK60 or EK80) and that they will all
    contain the same basic data type (power only, angle only, power+angle, or
    complex.)

    If the bottom detection files are colocated with the .raw data, it will
    also attempt to read those files. These files must be located in the same
    directory as the .raw files and they must follow the standard Simrad naming
    convention. Supported formats include only .bot and .xyz files (default
    preference is for .xyz.) While the underlying classes support reading .out
    files, this simplified interface does not.

    Args:
            files (list): List containing full paths to data file or files
                to be read. Required.

        Additional arguments can be passed to control what data is read from
        the file. The follow arguments will filter data when reading, jumping
        over datagrams that aren't specified to be read. Arguments can be
        combined

            frequencies (list): List of floats specifying the frequency or
                frequencies you want to read from the file. Data from other
                frequencies will be ignored. Set to None to read all frequencies.

                Default: None

            channel_ids (list): A list of strings that contain the unique
                channel IDs to read. Set to None to read all channels in the
                file.

                Default: None

            start_time (datetime64): Specify a start time if you do not want
                to start reading from the first ping. Set to None to start
                reading from the first ping.

                Default: None

            end_time (datetime64): Specify an end time if you do not want to read
                to the last ping.  Set to None to read through the last ping.

                Default: None

            start_ping (int): Specify starting ping number if you do not want
                to start reading at first ping. Set to None to start reading from
                the first ping. Ping numbers start at 1 and increment for each
                distinct transmission time encountered in the data file(s) passed
                to echosounder.read().

                Default: None

            end_ping (int): Specify end ping number if you do not want
                to read all pings. Set to None to read through the last ping.
                Ping numbers start at 1 and increment for each distinct transmission
                time encountered in the data file(s) passed to echosounder.read().

                Default: None

            nmea (bool): Set to True to store NMEA data. When set to False,
                all NMEA datagrams are skipped.

                Default: True


        These arguments also filter what data is stored, but they are applied after
        the filtering performed by the keywords above. These filters require reading
        and parsing of the raw datagrams so they are not as efficient as the filters
        above but hey will still allow you to manage memory usage.


            power (bool): Controls whether power data is stored. Set to True
                to store power data. False to ignore it.

                Default: True

            angles (bool): Controls whether angle data is stored. Set to True
                to store angle data. False to ignore it.

                Default: True

            complex (bool): Controls whether complex data is stored. Set to True
                to store cinplex data. False to ignore it.

                Default: True

            max_sample_count (int): Specify the max sample count to read if your
                data of interest is less than the total number of samples contained
                in the instrument files. Set to None to read all samples.

                Default: None

            start_sample (int): Specify starting sample number to store. Set to
                None to store samples starting from the first sample in the ping.

                Default: None

            end_sample (int): Specify ending sample number to store. Set to None to
                store through the last sample in the ping.

                Default: None

    """

    # if we're given a string, wrap it in a list
    if not isinstance(files, list):
        files = [files]

    #  set the default value for our data object
    data_object = None

    # Work through the list of input files
    for file in files:
        filename = os.path.normpath(file)

        # Determine what kind of data file we have
        try:
            data_type = _check_filetype(filename)
        except:
            raise FileNotFoundError("Unable to open file: " + filename)

        if data_object is None:
            #  This is the first file we're reading so we need to create the data object
            if data_type == SIMRAD_EK60:
                # This is an EK60 file, we're going to assume all files are EK60
                data_object = EK60.EK60()
            elif data_type == SIMRAD_EK80:
                # This is an EK80 file, we're going to assume all files are EK80
                data_object = EK80.EK80()
            else:
                # We don't know what this is
                raise UnknownFormatError("Unknown file type encountered: " + filename)

        #  check to make sure all of the files share the same file format
        elif ((data_type == SIMRAD_EK60 and isinstance(data_object, EK80.EK80)) or
              (data_type == SIMRAD_EK80 and isinstance(data_object, EK60.EK60))):
            # We've encountered a file with a different type than the initial file read
                raise TypeError("Mixed Ex80 and Ex60 data files encountered. The echosounder " +
                        "module does not support reading mixed data file formats at one time. " +
                        "Either read these files in separate calls to echosounder.read() or " +
                        "implement your code using the underlying EK60 and EK80 classes.")

        # Read the data file using the object for this data type
        data_object.append_raw(filename, **kwargs)

        #  now try to read the bottom data. We are assuming the .bot or .XYZ files are colocated
        #  with the .raw file and that they follow the normal Simrad naming convention.
        if data_type == SIMRAD_EK80:
            #  Simrad EK80 systems can generate both XYZ and.or .bot files
            bot_type, bot_files = simrad_utils.get_simrad_bottom_files(filename, data_object)
            if bot_type == 'BOT':
                data_object.read_bot(bot_files)
            elif bot_type == 'XYZ':
                for channel_id in bot_files:
                    data_object.read_xyz(channel_id, bot_files[channel_id])

        elif data_type == SIMRAD_EK60:
            #  Simrad EK60 systems do not generate XYZ files so we only check for .bot files
            _, bot_files = simrad_utils.get_simrad_bottom_files(filename, data_object,
                    skip_xyz=True)
            if bot_files:
                data_object.read_bot(bot_files)

    return data_object


def get_calibration_from_raw(data_object, **kwargs):
    '''get_calibration_from_raw returns a dictionary, keyed by channel ID,
    containing a calibration object populated with data extracted from the
    raw data contained in the provided data_object.

    If you want to use different calibration parameters than the ones in the
    raw data, you will want to call this function to get the initial calibration
    objects and then modify them as needed.

    Like all functions in the echosounder module, this function assumes that
    your data object contains only one type of data (power only, angle only,
    power+angle, or complex) and will return data from the first data type
    only.

    data_object (EK60 or EK80 object): Set this to an instance of the EK60 or
        EK80 object that you obtained after calling echosounder.read().

    absorption_method (str): Set this to a string specifying the method used
        for computing absorption. Available methods are:

        'A&M': Computes absorption using the equation describe in:

        Ainslie M. A., McColm J. G., "A simplified formula for viscous and
          chemical absorption in sea water", Journal of the Acoustical Society
          of America, 103(3), 1671-1672, 1998.

        'F&G': Computes absorption using the equation describe in:

        Francois R. E., Garrison G. R., "Sound absorption based on ocean
          measurements: Part II:Boric acid contribution and equation for
          total absorption", Journal of the Acoustical Society of America,
          72(6), 1879-1890, 1982.

        Default value is 'F&G'

    '''

    calibrations = {}

    for chan in data_object.raw_data:
        calibrations[chan] = data_object.raw_data[chan][0].get_calibration(**kwargs)

    return calibrations


def get_calibration_from_ecs(data_object, ecs_file, channel_map=None, **kwargs):
    '''get_calibration_from_ecs will returns a dictionary, keyed by channel ID,
    containing a calibration object populated with data extracted from an Echoview
    .ecs file. Calibration parameters not present or commented out in the .ecs file
    will be populated from the raw data contained in the provided data_object.


    Like all functions in the echosounder module, this function assumes that
    your data object contains only one type of data (power only, angle only,
    power+angle, or complex) and will return data from the first data type
    only.

    data_object (EK60 or EK80 object): Set this to an instance of the EK60 or
        EK80 object that you obtained after calling echosounder.read().

    ecs_file (str): Set this to the full path to the .ecs file you want to read.

    absorption_method (str): Set this to a string specifying the method used
        for computing absorption. Available methods are:

        'A&M': Computes absorption using the equation describe in:

        Ainslie M. A., McColm J. G., "A simplified formula for viscous and
          chemical absorption in sea water", Journal of the Acoustical Society
          of America, 103(3), 1671-1672, 1998.

        'F&G': Computes absorption using the equation describe in:

        Francois R. E., Garrison G. R., "Sound absorption based on ocean
          measurements: Part II:Boric acid contribution and equation for
          total absorption", Journal of the Acoustical Society of America,
          72(6), 1879-1890, 1982.

        Default value is 'F&G'

    '''

    calibrations = {}
    last_chan = None
    T = 1

    for chan in data_object.raw_data:
        calibrations[chan] = data_object.raw_data[chan][0].get_calibration(**kwargs)

        #  Generate the EV calibration label.
        #  First parse the channel ID for channel number
        chan_parts = chan.split('_')

        #  check if this is a new transceiver+transducer
        if last_chan is not None:
            if last_chan != chan:
                #  we have a new one, increment the counter
                T += 1
                last_chan = chan
        else:
            #  this is the first channel we have encountered
            last_chan = chan

        #  set the base label value
        ev_cal_label = "T%i" % (T)

        #  check if we need to add a channel number
        if len(chan_parts) > 1:
            #  yes, there is a channel number attached to the channel ID
            ev_cal_label += " (channel %s)" % (chan_parts[1])

        #  finally read the ecs file and update the params in our calibration
        ecs_file = os.path.normpath(ecs_file)
        calibrations[chan].read_ecs_file(ecs_file, ev_cal_label)
    return calibrations


def get_calibration_from_xml(data_object,xml_files,calibrations = None,
        apply_to_matching_channels = True):

    '''get_calibration_from_xml returns a dictionary, keyed by channel ID,
    containing a calibration object populated with data extracted from the
    EK80 xml files provided.

    The function will use the calibration parameters in the raw data to build
    the calibration objects, and overwrite the appropriate parameters with the
    values from the xml files.

    Where multiple xml files for the same channel are provided, the function will
    average the calibration parameters for each frequency.

    data_object (EK60 or EK80 object): Set this to an instance of the EK60 or
        EK80 object that you obtained after calling echosounder.read().

    xml_files (str): Set this to the full path to the .xml file you want to read
        or provide a list of xml files.

    calibration (dict): Provide an already existing calibration dictionary keyed
        by channel ID to append new channels.

    apply_to_matching_channels (bool): Set this to True to apply the calibration
        to all matching channels, i.e., active to passive.

    '''

    # if we're given a string, wrap it in a list
    if not isinstance(xml_files, list):
        xml_files = [xml_files]

    # Initiate the calibrations dictionary if not provided an already existing dictionary
    if calibrations is None:
        calibrations = {}

    # Loop through the xml files and fill in the dictionary with the matching
    # data_object channel_id as the key
    for file in xml_files:

        # Read the calibration file
        cal = EK80.ek80_calibration()
        cal.read_xml_file(file)
        # Get the channel name from the calibration file and find the corresponding channel_id
        # in the data_object
        try: # If the channel ends in a number, include it in the channel ID
            int(cal.channel_name.split('-')[-1])
            xml_chan = cal.channel_name.split(' ')[0]+'_'+cal.channel_name.split('-')[-1]
        except:
            xml_chan = cal.channel_name.split(' ')[0]
        chan  = [s for s in data_object.channel_ids if xml_chan in s]

        # Check to see if this xml file matches a channel
        if chan:
            # It does
            chan = chan[0]
        else:
            # It doesn't so we skip this file
            continue

        # If the channel pulse form matches the pulse form of the data, add the calibration
        # to the dictionary
        match = _compare_pulse(data_object.get_channel_data()[chan][0],cal)
        if match:
            if chan not in calibrations.keys():
                calibrations[chan] = []
            calibrations[chan].append(cal)

    # Create averaged calibrations for channels where multiple xml files exist
    for chan in calibrations.keys():

        # Check in case we've provided a calibration dictionary that already has objects in it
        if isinstance(calibrations[chan],list):

            # If there are multiple cals for the same channel, the variables from the calibration
            # results tree are averaged
# If there are multiple cals for the same channel, the variables from the calibration
            # results tree are averaged
            if (len(calibrations[chan]) > 1):
                warnings.warn('Multiple calibrations for channel: ' + chan +
                        ' ::: Calibration parameters will be interpolated and averaged across total bandwidth.')

                # Create a new calibration object to store the merged calibration with the rest
                # of the properties from the first calibration
                merged_cal = calibrations[chan][0]
                
                # 1. Establish a master frequency grid representing the union of all bandwidths
                all_freqs = []
                for cal in calibrations[chan]:
                    freq = cal.frequency
                    if not isinstance(freq, np.ndarray):
                        freq = np.array([freq])
                    all_freqs.append(freq)
                
                merged_frequency = np.unique(np.concatenate(all_freqs))

                # Loop through the calibration attributes that need to be averaged
                for attr in ['gain', 'sa_correction', 'beam_width_alongship', 'beam_width_athwartship',
                        'angle_offset_alongship', 'angle_offset_athwartship']:

                    # List to hold interpolated arrays for the current attribute
                    interp_values = []

                    # For each calibration in the list for the channel...
                    for cal in calibrations[chan]:

                        # get the attribute as a function of frequency
                        current_frequency, current_val = cal.frequency, getattr(cal, attr)

                        # If the frequency/attribute is not an array (CW data), make it an array
                        if not isinstance(current_frequency, np.ndarray):
                            current_frequency = np.array([current_frequency])

                        if not isinstance(current_val, np.ndarray):
                            current_val = np.array([current_val])

                        # 2. Interpolate, strictly assigning np.nan for out-of-bounds frequencies
                        interp_val = np.interp(
                            merged_frequency, 
                            current_frequency, 
                            current_val, 
                            left=np.nan, 
                            right=np.nan
                        )
                        interp_values.append(interp_val)
                        
                    # Convert to a 2D numpy array where each row represents one calibration file
                    interp_values = np.array(interp_values)

                    # 3. Average the interpolated values. np.nanmean ignores NaNs, fulfilling the logic requirement.
                    if attr in ['gain', 'sa_correction']:
                        # Power mean in dB (Warning: ignore warnings about taking mean of all-NaN slices)
                        with warnings.catch_warnings():
                            warnings.simplefilter("ignore", category=RuntimeWarning)
                            linear_mean = np.nanmean(10 ** (interp_values / 10.0), axis=0)
                            merged_val = 10 * np.log10(linear_mean)
                    else: 
                        # Linear mean for other attributes
                        with warnings.catch_warnings():
                            warnings.simplefilter("ignore", category=RuntimeWarning)
                            merged_val = np.nanmean(interp_values, axis=0)

                    if len(merged_val) == 1:
                        merged_val = merged_val[0]
                        
                    # Set the merged attribute values to the merged calibration object
                    merged_cal.__setattr__(attr, merged_val)

                if len(merged_frequency) > 1:
                    merged_cal.__setattr__('frequency', merged_frequency)

                # Assign the merged calibration to the channel in the calibrations dictionary
                calibrations[chan] = merged_cal

            # If there is only one calibration for the channel, just pull it out of the list
            else:
                calibrations[chan] = calibrations[chan][0]

    # If apply_to_matching_channels is set to True, apply the calibration to all matching channels,
    # i.e., active to passive
    if apply_to_matching_channels:

        # For each channel still missing a calibration, find the matching channel
        for chan in [s for s in data_object.channel_ids if s not in calibrations.keys()]:
            matching_channel = _find_matching_channel(data_object,chan)

            # If a matching channel is found, apply the calibration to the missing channel
            if matching_channel is not None and matching_channel in calibrations:
                calibrations[chan] = calibrations[matching_channel]

    # Warn if there are channels in the data object that do not have a calibration
    for chan in  [s for s in data_object.channel_ids if s not in calibrations.keys()]:
        warnings.warn("No calibration found for channel: " + chan)

    return calibrations


def get_Sv(data_object, linear=False, **kwargs):
    '''get_Sv returns a dictionary, keyed by channel ID, containing processed
        data object(s) containing Sv data.

        The frequencies, channel_ids, ping, and time range keywords can be set
        to limit what data is returned. These keywords can be applied together.
        Note that is generally more efficient to filter data when calling
        echosounder.read()

        frequencies (list): Set this to a list containing the frequencies to
            return data from.

            Default: None (return all frequencies)

        channel_ids (list): Set this to a list containing the channel IDs to
            return data from.

            Default: None (return all channels)

        start_time (datetime64): Set to a numpy datetime64 oject specifying
            the start time of the data to convert. All data between the start
            and end time will be returned. If set to None, the start time is
            the first ping.

            Default: None

        end_time (datetime64): Set to a numpy datetime64 oject specifying
            the end time of the data to convert. All data between the start
            and end time will be returned. If set to None, the end time is
            the last ping.

            Default: None

        start_ping (int): Set to an integer specifying the first ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the first ping is set as the start ping.

            Default: None

        end_ping (int): Set to an integer specifying the end ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the last ping is set as the end ping.

            Default: None

        return_indices (np.array uint32): Set this to a numpy array that contains
            the index values to return in the processed data object. This can be
            used for more advanced anipulations where start/end ping/time are
            inadequate.

            Default: None (return all pings)

        calibration (EK80.ek80_calibration): Set to an instance of
            EK80.ek80_calibration containing the calibration parameters
            you want to use when transforming to Sv/sv. If no calibration
            object is provided, the values will be extracted from the raw
            data.

            Default: None

        tvg_correction (bool): Set to True to apply TVG range correction.
            Typically you want to leave this at True.

            Default: True

        return_depth (bool): Set to True to return a processed_data object
            with a depth axis. When False, the processed_data object has
            a range axis.

            Default: False

        heave_correct (bool): Set to True to return a processed_data object
            that has heave correction applied. Heave correction shifts samples
            vertically to compensate for the sounder platform's vertical motion.
            Heave corrected data is always returned as depth.

            Default: False
    '''

    return _get_processed_data(data_object, 'Sv', linear=False, **kwargs)


def get_sv(data_object, linear=True, **kwargs):
    '''get_sv returns a dictionary, keyed by channel ID, containing processed
        data object(s) containing sv data.

        The frequencies, channel_ids, ping, and time range keywords can be set
        to limit what data is returned. These keywords can be applied together.
        Note that is generally more efficient to filter data when calling
        echosounder.read()

        frequencies (list): Set this to a list containing the frequencies to
            return data from.

            Default: None (return all frequencies)

        channel_ids (list): Set this to a list containing the channel IDs to
            return data from.

            Default: None (return all channels)

        start_time (datetime64): Set to a numpy datetime64 oject specifying
            the start time of the data to convert. All data between the start
            and end time will be returned. If set to None, the start time is
            the first ping.

            Default: None

        end_time (datetime64): Set to a numpy datetime64 oject specifying
            the end time of the data to convert. All data between the start
            and end time will be returned. If set to None, the end time is
            the last ping.

            Default: None

        start_ping (int): Set to an integer specifying the first ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the first ping is set as the start ping.

            Default: None

        end_ping (int): Set to an integer specifying the end ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the last ping is set as the end ping.

            Default: None

        return_indices (np.array uint32): Set this to a numpy array that contains
            the index values to return in the processed data object. This can be
            used for more advanced anipulations where start/end ping/time are
            inadequate.

            Default: None (return all pings)

        calibration (EK80.ek80_calibration): Set to an instance of
            EK80.ek80_calibration containing the calibration parameters
            you want to use when transforming to Sv/sv. If no calibration
            object is provided, the values will be extracted from the raw
            data.

            Default: None

        tvg_correction (bool): Set to True to apply TVG range correction.
            Typically you want to leave this at True.

            Default: True

        return_depth (bool): Set to True to return a processed_data object
            with a depth axis. When False, the processed_data object has
            a range axis.

            Default: False

        heave_correct (bool): Set to True to return a processed_data object
            that has heave correction applied. Heave correction shifts samples
            vertically to compensate for the sounder platform's vertical motion.
            Heave corrected data is always returned as depth.

            Default: False
    '''

    return _get_processed_data(data_object, 'Sv', linear=True,**kwargs)


def get_Sp(data_object, linear=True, **kwargs):
    '''get_Sp returns a dictionary, keyed by channel ID, containing processed
        data object(s) containing Sp data.

        The frequencies, channel_ids, ping, and time range keywords can be set
        to limit what data is returned. These keywords can be applied together.
        Note that is generally more efficient to filter data when calling
        echosounder.read()

        frequencies (list): Set this to a list containing the frequencies to
            return data from.

            Default: None (return all frequencies)

        channel_ids (list): Set this to a list containing the channel IDs to
            return data from.

            Default: None (return all channels)

        start_time (datetime64): Set to a numpy datetime64 oject specifying
            the start time of the data to convert. All data between the start
            and end time will be returned. If set to None, the start time is
            the first ping.

            Default: None

        end_time (datetime64): Set to a numpy datetime64 oject specifying
            the end time of the data to convert. All data between the start
            and end time will be returned. If set to None, the end time is
            the last ping.

            Default: None

        start_ping (int): Set to an integer specifying the first ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the first ping is set as the start ping.

            Default: None

        end_ping (int): Set to an integer specifying the end ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the last ping is set as the end ping.

            Default: None

        return_indices (np.array uint32): Set this to a numpy array that contains
            the index values to return in the processed data object. This can be
            used for more advanced anipulations where start/end ping/time are
            inadequate.

            Default: None (return all pings)

        calibration (EK80.ek80_calibration): Set to an instance of
            EK80.ek80_calibration containing the calibration parameters
            you want to use when transforming to Sp/sp. If no calibration
            object is provided, the values will be extracted from the raw
            data.

            Default: None

        tvg_correction (bool): Set to True to apply TVG range correction.
            Typically you want to leave this at True.

            Default: True

        return_depth (bool): Set to True to return a processed_data object
            with a depth axis. When False, the processed_data object has
            a range axis.

            Default: False

        heave_correct (bool): Set to True to return a processed_data object
            that has heave correction applied. Heave correction shifts samples
            vertically to compensate for the sounder platform's vertical motion.
            Heave corrected data is always returned as depth.

            Default: False
    '''

    return _get_processed_data(data_object, 'Sp', linear=False, **kwargs)


def get_sp(data_object, linear=True, **kwargs):
    '''get_sp returns a dictionary, keyed by channel ID, containing processed
        data object(s) containing sp data.

        The frequencies, channel_ids, ping, and time range keywords can be set
        to limit what data is returned. These keywords can be applied together.
        Note that is generally more efficient to filter data when calling
        echosounder.read()

        frequencies (list): Set this to a list containing the frequencies to
            return data from.

            Default: None (return all frequencies)

        channel_ids (list): Set this to a list containing the channel IDs to
            return data from.

            Default: None (return all channels)

        start_time (datetime64): Set to a numpy datetime64 oject specifying
            the start time of the data to convert. All data between the start
            and end time will be returned. If set to None, the start time is
            the first ping.

            Default: None

        end_time (datetime64): Set to a numpy datetime64 oject specifying
            the end time of the data to convert. All data between the start
            and end time will be returned. If set to None, the end time is
            the last ping.

            Default: None

        start_ping (int): Set to an integer specifying the first ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the first ping is set as the start ping.

            Default: None

        end_ping (int): Set to an integer specifying the end ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the last ping is set as the end ping.

            Default: None

        return_indices (np.array uint32): Set this to a numpy array that contains
            the index values to return in the processed data object. This can be
            used for more advanced anipulations where start/end ping/time are
            inadequate.

            Default: None (return all pings)

        calibration (EK80.ek80_calibration): Set to an instance of
            EK80.ek80_calibration containing the calibration parameters
            you want to use when transforming to Sv/sv. If no calibration
            object is provided, the values will be extracted from the raw
            data.

            Default: None

        tvg_correction (bool): Set to True to apply TVG range correction.
            Typically you want to leave this at True.

            Default: True

        return_depth (bool): Set to True to return a processed_data object
            with a depth axis. When False, the processed_data object has
            a range axis.

            Default: False

        heave_correct (bool): Set to True to return a processed_data object
            that has heave correction applied. Heave correction shifts samples
            vertically to compensate for the sounder platform's vertical motion.
            Heave corrected data is always returned as depth.

            Default: False
    '''

    return _get_processed_data(data_object, 'Sp', linear=True, **kwargs)


def get_power(data_object, linear=False, **kwargs):
    '''get_power returns a dictionary, keyed by channel ID, containing processed
        data object(s) containing power data.

        The frequencies, channel_ids, ping, and time range keywords can be set
        to limit what data is returned. These keywords can be applied together.
        Note that is generally more efficient to filter data when calling
        echosounder.read()

        frequencies (list): Set this to a list containing the frequencies to
            return data from.

            Default: None (return all frequencies)

        channel_ids (list): Set this to a list containing the channel IDs to
            return data from.

            Default: None (return all channels)

        start_time (datetime64): Set to a numpy datetime64 oject specifying
            the start time of the data to convert. All data between the start
            and end time will be returned. If set to None, the start time is
            the first ping.

            Default: None

        end_time (datetime64): Set to a numpy datetime64 oject specifying
            the end time of the data to convert. All data between the start
            and end time will be returned. If set to None, the end time is
            the last ping.

            Default: None

        start_ping (int): Set to an integer specifying the first ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the first ping is set as the start ping.

            Default: None

        end_ping (int): Set to an integer specifying the end ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the last ping is set as the end ping.

            Default: None

        return_indices (np.array uint32): Set this to a numpy array that contains
            the index values to return in the processed data object. This can be
            used for more advanced anipulations where start/end ping/time are
            inadequate.

            Default: None (return all pings)

        calibration (EK80.ek80_calibration): Set to an instance of
            EK80.ek80_calibration containing the calibration parameters
            you want to use when transforming to Sv/sv. If no calibration
            object is provided, the values will be extracted from the raw
            data.

            Default: None

        linear (bool): Set to True to return data in linear units.

            Default: False

        tvg_correction (bool): Set to True to apply TVG range correction.
            Typically you want to leave this at True.

            Default: True

        return_depth (bool): Set to True to return a processed_data object
            with a depth axis. When False, the processed_data object has
            a range axis.

            Default: False

        heave_correct (bool): Set to True to return a processed_data object
            that has heave correction applied. Heave correction shifts samples
            vertically to compensate for the sounder platform's vertical motion.
            Heave corrected data is always returned as depth.

            Default: False
    '''

    return _get_processed_data(data_object, 'power', linear=linear, **kwargs)


def get_angles(data_object, **kwargs):
    '''get_angles returns a dictionary, keyed by channel ID, containing processed
        data object(s) containing physical angle data.

        The frequencies, channel_ids, ping, and time range keywords can be set
        to limit what data is returned. These keywords can be applied together.
        Note that is generally more efficient to filter data when calling
        echosounder.read()

        frequencies (list): Set this to a list containing the frequencies to
            return data from.

            Default: None (return all frequencies)

        channel_ids (list): Set this to a list containing the channel IDs to
            return data from.

            Default: None (return all channels)

        start_time (datetime64): Set to a numpy datetime64 oject specifying
            the start time of the data to convert. All data between the start
            and end time will be returned. If set to None, the start time is
            the first ping.

            Default: None

        end_time (datetime64): Set to a numpy datetime64 oject specifying
            the end time of the data to convert. All data between the start
            and end time will be returned. If set to None, the end time is
            the last ping.

            Default: None

        start_ping (int): Set to an integer specifying the first ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the first ping is set as the start ping.

            Default: None

        end_ping (int): Set to an integer specifying the end ping number
            to return. All pings between the start and end ping will be
            returned. If set to None, the last ping is set as the end ping.

            Default: None

        return_indices (np.array uint32): Set this to a numpy array that contains
            the index values to return in the processed data object. This can be
            used for more advanced anipulations where start/end ping/time are
            inadequate.

            Default: None (return all pings)

        calibration (EK80.ek80_calibration): Set to an instance of
            EK80.ek80_calibration containing the calibration parameters
            you want to use when transforming to Sv/sv. If no calibration
            object is provided, the values will be extracted from the raw
            data.

            Default: None

        return_depth (bool): Set to True to return a processed_data object
            with a depth axis. When False, the processed_data object has
            a range axis.

            Default: False

        heave_correct (bool): Set to True to return a processed_data object
            that has heave correction applied. Heave correction shifts samples
            vertically to compensate for the sounder platform's vertical motion.
            Heave corrected data is always returned as depth.

            Default: False
    '''

    return _get_processed_data(data_object, 'angles', **kwargs)


def _get_processed_data(data_object, data_type, fm_frequency_domain=True, calibration=None,
        frequencies=None, channel_ids=None, heave_correct=False, **kwargs):
    '''_get_processed_data is an internal function that returns a dictionary,
        keyed by channel ID, containing processed_data objects containing the
        specified data type. Valid data_types are 'Sv', 'power', 'Sp', 'angles'

        This function is not intended to be called directly. Instead you should
        call get_Sv(), get_Sp(), get_power(), etc.
    '''

    data = {}

    #  iterate thru all of the channels
    for chan in data_object.raw_data:

        #  get a reference to this channel's raw data
        raw_obj = data_object.raw_data[chan][0]

        #  check if we're returning this channel
        return_chan = _filter_channel(chan, raw_obj, channel_ids, frequencies, data_type)

        # if we are, get all of the data
        if return_chan:
            #  first, get a calibration object for this channel
            if calibration:
                if chan in calibration:
                    #  one is provided
                    cal_obj = calibration[chan]
                else:
                    #  cal dict provided but this channel not in it - get from raw
                    cal_obj = raw_obj.get_calibration()
            else:
                #  no cal provided - get one using the raw file parameters
                cal_obj = raw_obj.get_calibration()
                
            #  then get the data - stick Sv, Sp, and power types 
            if data_type == 'Sv':
                if raw_obj.is_fm() & fm_frequency_domain:
                    p_data = raw_obj.get_Svf(calibration=cal_obj, **kwargs)
                else:
                    p_data = raw_obj.get_Sv(calibration=cal_obj, **kwargs)
            elif data_type == 'Sp':
                p_data = raw_obj.get_Sp(calibration=cal_obj, **kwargs)
            elif data_type == 'power':
                p_data = raw_obj.get_power(calibration=cal_obj, **kwargs)
            elif data_type == 'angles':
                # when getting angles, a tuple of processed_data objects is returned
                # (p_data_alongship, p_data_athwartship)
                p_data = raw_obj.get_physical_angles(calibration=cal_obj, **kwargs)

            #  add the navigation and motion data - this takes the asynchronous NMEA
            #  and motion data and interpolates it onto the ping time axis and stores
            #  the data in the processed data object.

            #  deal with the angle data tuple by making everything a tuple for this step
            if not isinstance(p_data, tuple):
                p_data = (p_data,)
            
            for p in p_data:

                #  first add the NMEA data - This will add the position, speed, attitude,
                #  and distance meta-types (see instruments.util.nmea_data for more info)
                p.set_navigation(data_object.nmea_data)

                #  then add the motion data - we'll check if we have lat data from the NMEA
                #  data and if not, try to get it from the motion data. Some EK80 configurations
                #  may only store lat/lon in the motion data and not as NMEA data.
                if not hasattr(p, 'latitude'):
                    #  we didn't get lat/lon from the NMEA data so try to get it from motion data
                    p.set_motion(data_object.motion_data, motion_attributes=['pitch',
                            'roll', 'heave', 'heading', 'latitude', 'longitude'])
                else:
                    #  we have lat (and presumably lon) data so we just get the "regular" motion
                    #  data (pitch, roll, heave, heading)
                    p.set_motion(data_object.motion_data)

                #  apply heave correction if needed - this has no effect if heave
                #  data is not available.
                if heave_correct:
                    p.heave_correct()

                #  get the bottom detection data. This method will automatically
                #  correct depths as needed if the calibration sound speed is different
                #  from the sound speed at the time of collection.
                bottom_line = raw_obj.get_bottom(calibration=cal_obj, **kwargs)

                if bottom_line is not None:
                    #  Bottom data is always recorded as depth with heave correction applied,
                    #  so we need to back out transducer Z offset and/or heave (if applicable)
                    #  when returning sample data with range as the vertical axis
                    v_axis = p.get_v_axis()[1]
                    if v_axis == 'range':
                        #  the transducer_draft attribute of the bottom line contains both
                        #  the z offset and heave. We simply subtract these values from the
                        #  line data to get the line in range.
                        bottom_line = bottom_line - bottom_line.transducer_draft
                    else:
                        #  we're returning data as depth. We don't need to back out transducer
                        #  z offset, but we have to back out heave correction if the user has
                        #  not heave corrected the sample data
                        if not heave_correct:
                            #  heave correction is not set, subtract heave from the bottom line
                            if hasattr(p,'heave'):
                                bottom_line = bottom_line - p.heave

                    #  add the bottom detection line to the processed data object
                    p.add_data_attribute('bottom_line', bottom_line)

            #  unpack the temporary tuple we just created when adding the nav and motion data
            if data_type == 'angles':
                #  angles are supposed to be returned as a tuple so do nothing
                data[chan] = p_data
            else:
                #  unpack power/Sv/Sp objects
                data[chan] = p_data[0]

    return data


def get_rawfile_info(file, force_full_read=False):
    '''get_rawfile_info tries to efficiently extract some basic information about raw
    files. This function first looks for an .idx file to extract start/end ping and time
    information and then reads the header only of the raw file. This is pretty quick.
    If an .idx file is not available, it will fall back to using the EK*0 classes to
    read the .raw file. This will be slower since while little data will be stored, the
    entire file will still have to be read.

    NOTE! For EK80 formatted files, the pulse form (CW/FM) and channel mode (active/passive)
          are extracted from the initial parameters datagram and represent the state of the
          system when the raw file was created. The EK80 software should prevent these
          parameters from changing while the system is recording, but there is no guarantee
          that this is the case for all files.

          For EK60 formatted files, the channel mode (active/passive) is extracted from the
          first ping and represent the state of the system when the first ping was recorded.

          The EK60 and EK80 file formats have evolved over time and fields have been added.
          Older files may not have all fields populated.
    
    Args:
        file (str): provide a string defining the full path to the raw file to read


    A dictionary is returned containg the following keys:

        File Attributes:

        raw_file_name - the name of the raw file
        idx_file_name - the name of the idx file (None if no idx file exists)
        raw_file_size_bytes - the size of the raw file in bytes
        start_time - the time of the first ping as datetime64
        end_time - the time of the last ping as datetime64
        start_ping - the starting ping in the file - If an .idx file is available,
            the ping numbers are based on the collection software's global ping counter.
            If the .idx file is not available, the ping numbers are relative to the
            data file and start at 1.
        end_ping - the last ping in the file - If an .idx file is available,
            the ping numbers are based on the collection software's global ping counter.
            If the .idx file is not available, the ping numbers are relative to the
            data file.
        n_pings - the total number of pings in the file
        channels - a list containing the channel IDs that are in the file
        application_name - a string containing the name of the application that recorded the data.
        application_version - a string containing the application version number
        file_format_version - a string containing the file format version number
        ping_mode - The operational mode the EK80 system was operating in. Values are (I think)
            'Normal', 'Replay', 'Sequence'
        time_bias - Not sure what this is but would guess it is some global time bias applied to
            all data in the file? Not sure what the units are. I have only seen values of 0.

        Channel Attributes:
            
        configuration - a dict, keyed by channel ID, that contains the channel's
            configuration parameters. Each channel will have the following keys:

                transceiver_name - The name of the transceiver hardware which is comprised
                    of the transeciver type and serial number. This will be unique for all
                    transceivers.
                transceiver_type - The class of transceiver hardware:
                    GPT, WBT, WBT MINI, WBT TUBE, WBT HP, WBT LF, WBAT, SBT, ...
                serial_number - the transceiver serial number.
                channel_id - The string that uniquely identifies the channel, usually comprised
                    of the hardware type, serial number, maybe some multiplexing info, and
                    transducer name.
                channel_id_short - 
                market_segment - 'scientific' or 'commercial' (?)
                impedance - the transceiver impedance. This attribute was added in later EK80
                    file formats. If missing, it defaults to 1000 ohms which may or may not
                    be correct depending on the manufacture date of your hardware. Early WBTs
                    had an impedance of 1000 ohms. Later versions switched to 5400 ohms. It is
                    unclear if this change coincided with the addition of impedance to the data
                    file or if data files exist where the xcvr impedance is 5400 but the data
                    files still lack the impedance information.
                multiplexing - 0 and I assume 1? 0 is not multiplexing
                rx_sample_frequency - The sampling frrequency of the Rx ADC
                ip_address - The IP address of the transceiver when the data were recorded.
                ethernet_address - The MAC address of the transceiver
                transceiver_software_version - The firmware version running on the transceiver
                fpga_tx_firmware_ver - The FPGA firmware version for the Tx DSP subsystem
                fpga_rx_firmware_ver - The FPGA firmware version for the Rx DSP subsystem
                transceiver_number - For EK80 files, the number indicating the order the transceiver
                    was added to the system (?), starting at 1. This number is tied to the
                    physical hardware and EK80 channels that share a transceiver will have the
                    same transceiver number. For EK60 files, this is really the channel number
                    which starts at 1 and increments for each configured channel. This is not
                    tied to the hardware. When multiplexing with the EK60, each MUX channel
                    (same GPT) will have a different channel number.
                max_tx_power_transceiver - The maximum power in watts the 
                hw_channel_configuration - A number representing the hardware configuration.
                    I do not have any info on this.

                The following attributes are extracted from the initial parameters datagram from
                an EK80 file or from the first ping ensemble in a EK60 file. They may not represent
                the values throught the file.

                channel_mode - 'active' or 'passive'
                pulse_form - CW or FM
                pulse_duration - The pulse duration for the first ping 
                frequency - CW channels only - the frequency of the Tx pulse
                frequency_start - FM channels only - the starting frequency of the Tx pulse 
                frequency_end - FM channels only - the starting frequency of the Tx pulse 
                pulse_duration - The duration of the Tx pulse in seconds
                sample_interval - The duration of the Rx sampling interval in seconds.
                transmit_power - The power in watts of the Tx signal
                slope - EK80 only - The slope of the Tx signal
                sound_velocity - The sound velocity in m/s

                transducer - a dict containing this channel's transducer information. It contains
                    the following keys:

                    transducer_name
                    transducer_serial_number
                    transducer_frequency - The transducer's center frequency
                    transducer_frequency_minimum - The transducer's minimum recommended Tx frequency
                    transducer_frequency_maximum - The transducer's maximum recommended Tx frequency
                    max_tx_power_transducer - The transducer's maximum recommened Tx power rating
                    transducer_beam_type - A list containing he transducer beam type as an integer as
                        written in the data file and as a string interpreted from that. I do not have
                        an official list from Simrad/Kongsberg to map the number to a name, but have
                        gathered what I can from the documenation.
                    transducer_custom_name
                    transducer_mounting - 'Drop Keel', 'Hull Mounted', ...
                    transducer_orientation
                    transducer_offset_x - athwartship (?) transducer offset from the GPS antenna
                    transducer_offset_y - alongship (?) transducer offset from the GPS antenna
                    transducer_offset_z - vertical (?) transducer offset from the GPS antenna
                    transducer_alpha_x - transducer rotation around the athwartship axis (?)
                    transducer_alpha_y - transducer rotation around the alongship axis (?)
                    transducer_alpha_z - transducer rotation around the vertical axis (?)

    '''

    #  Define lists containing the EK80 configuration fields to extract. Also create dicts
    #  to map EK60 params to the EK80 fields.
    EK80_FILE_CONFIG_FIELDS = ['application_name',
                               'application_version',
                               'file_format_version',
                               'ping_mode',
                               'time_bias']

    EK60_FILE_CONFIG_MAP = {'application_name':'sounder_name',
                            'application_version':'version'}

    EK80_XCVR_CONFIG_FIELDS = ['transceiver_name',
                               'ip_address',
                               'market_segment',
                               'serial_number',
                               'impedance',
                               'multiplexing',
                               'rx_sample_frequency',
                               'transceiver_type',
                               'ethernet_address',
                               'transceiver_software_version',
                               'transceiver_number',
                               'channel_id',
                               'channel_id_short',
                               'max_tx_power_transceiver',
                               'hw_channel_configuration']
    
    EK60_XCVR_CONFIG_MAP = {'channel_id':'channel_id',
                            'transceiver_software_version':'gpt_software_version'}
    
    EK80_INITIAL_PARAM_FIELDS = ['channel_mode',
                                 'pulse_form',
                                 'frequency',
                                 'frequency_start',
                                 'frequency_end',
                                 'pulse_duration',
                                 'sample_interval',
                                 'transmit_power',
                                 'slope',
                                 'sound_velocity']

    EK80_XDCR_CONFIG_FIELDS = ['transducer_name',
                               'transducer_serial_number',
                               'transducer_frequency',
                               'transducer_frequency_minimum',
                               'transducer_frequency_maximum',
                               'max_tx_power_transducer',
                               'transducer_beam_type',
                               'transducer_custom_name',
                               'transducer_mounting',
                               'transducer_orientation',
                               'transducer_offset_x',
                               'transducer_offset_y',
                               'transducer_offset_z',
                               'transducer_alpha_x',
                               'transducer_alpha_y',
                               'transducer_alpha_z']
    
    EK60_XDCR_CONFIG_MAP = {'transducer_frequency':'frequency',
                            'transducer_frequency_minimum':'frequency',
                            'transducer_frequency_maximum':'frequency',
                            'transducer_beam_type':'beam_type',
                            'transducer_offset_x':'pos_x',
                            'transducer_offset_y':'pos_y',
                            'transducer_offset_z':'pos_z',
                            'transducer_alpha_x':'dir_x',
                            'transducer_alpha_y':'dir_y',
                            'transducer_alpha_z':'dir_z'}

    
    #  normalize the input file path
    filename = os.path.normpath(file)

    #  start building the return dict
    file_info = {}
    file_info['raw_file_name'] = filename

    # first check if we have an .idx file - this is by far the fastest way
    # to get some basic info about a raw file
    file_root, _ = os.path.splitext(filename)
    idx_file = file_root + '.idx'
    if os.path.isfile(idx_file):
        has_idx = True
        file_info['idx_file_name'] = idx_file
    else:
        has_idx = False
        file_info['idx_file_name'] = None

    # Determine what kind of data file we have
    try:
        data_type = _check_filetype(filename)
    except:
        raise FileNotFoundError("Unable to open file: " + filename)

    # Get the raw file size in bytes
    file_info['raw_file_size_bytes'] = os.path.getsize(filename)

    #  create a data object based on file type
    if data_type == SIMRAD_EK60:
        # This is an EK60 file
        data_object = EK60.EK60()
        file_info['file_format'] = 'EK60'
    elif data_type == SIMRAD_EK80:
        # This is an EK80 file
        data_object = EK80.EK80()
        file_info['file_format'] = 'EK80'
    else:
        # We don't know what this is
        raise UnknownFormatError("Unknown file type encountered: " + filename)

    # Get info on this file - if an idx file is available, we use that
    if has_idx:
        try:
            #  read the idx file to get the time and ping span
            idx_data = data_object.read_idx(idx_file)
            pings = list(idx_data.keys())
            file_info['start_time'] = idx_data[pings[0]]['timestamp']
            file_info['end_time'] = idx_data[pings[-1]]['timestamp']
            file_info['start_ping'] = pings[0]
            file_info['end_ping'] = pings[-1]
            file_info['n_pings'] = pings[-1] - pings[0]
        except:
            # That didn't work - we'll just act like we don't have an idx file
            has_idx = False
        
    # next, read the rawfile header to extract info about the channels
    try:
        fid = RawSimradFile(filename, 'r')
    except:
        raise IOError('Unable to open raw file ' + filename + ' for reading.')

    # read the config header which is always the first datagram in the rawfile
    header = fid.read(1)
    
    if data_type == SIMRAD_EK80:
        # The newer raw format of the EK80 and related systems has an XML based header
        # with significantly more information than the EK60 style raw file and it has
        # the "initialparameter" datagram that provides info about some of the initial
        # channel settings. Use data from both to construct the return data.

        # Sanity check - if the header is not a configuration datagram, bail.
        if 'configuration' not in header:
            raise IOError('Unknown EK80 file format. Configuration header not found!')

        # Get the channels and create the configuration dictionary
        file_info['channels'] = list(header['configuration'].keys())
        file_info['configuration'] = {}

        # Set the application_name entry to None to indicate the file level attributes
        # have not been populated
        file_info['application_name'] = None

        # loop thru the channels to extract attributes for each channel
        for chan in file_info['channels']:
            #  create the configuration dict for this channel
            file_info['configuration'][chan] = {}

            # Check if we have parsed the attributes that are common across channels
            if file_info['application_name'] == None:
                # No, this must be the first channel we're parsing. Do the common attributes.
                for field in EK80_FILE_CONFIG_FIELDS:
                    try:
                        file_info[field] = header['configuration'][chan][field]
                    except:
                        file_info[field] = None

            # Add the transceiver configuration fields
            for field in EK80_XCVR_CONFIG_FIELDS:
                try:
                    file_info['configuration'][chan][field] = header['configuration'][chan][field]
                except:
                    if field == 'impedance':
                        # set the impedance to 1000 if the attribute is missing from the file
                        file_info['configuration'][chan][field] = 1000
                    else:
                        file_info['configuration'][chan][field] = None

            #  get the FPGA firmware versions
            try:
                xcvr_version_info = header['configuration'][chan]['transceiver_version'].split('\r\n')
                try:
                    file_info['configuration'][chan]['fpga_tx_firmware_ver'] = xcvr_version_info[8].split(":")[1].strip()
                except:
                    file_info['configuration'][chan]['fpga_tx_firmware_ver'] = 'Unable to parse'
                try:
                    file_info['configuration'][chan]['fpga_rx_firmware_ver'] = xcvr_version_info[9].split(":")[1].strip()
                except:
                    file_info['configuration'][chan]['fpga_rx_firmware_ver'] = 'Unable to parse'
            except:
                file_info['configuration'][chan]['fpga_tx_firmware_ver'] = None
                file_info['configuration'][chan]['fpga_rx_firmware_ver'] = None

            # Add the transducer information
            file_info['configuration'][chan]['transducer'] = {}
            for field in EK80_XDCR_CONFIG_FIELDS:
                try:
                    if field == 'transducer_beam_type':
                        # Add the beam type name as we know it to the numerical type
                        beam_type = header['configuration'][chan][field]
                        # set the name based on the type
                        if beam_type == 0:
                            type_name = 'Single Beam : 1 sector'
                        elif beam_type == 1:
                            type_name = 'Split Beam : 4 sector'
                        elif beam_type == 17:
                            type_name = 'Split Beam : 3 sector'
                        elif beam_type in [49,65,81]:
                            type_name = 'Split Beam : 3 sector with center element'
                        else:
                            type_name = 'Split Beam : Unknown sector configuration.'
                            
                        file_info['configuration'][chan]['transducer'][field] = [beam_type, type_name]
                    else:
                        file_info['configuration'][chan]['transducer'][field] = header['configuration'][chan][field]
                except:
                    file_info['configuration'][chan]['transducer'][field] = None

        # Now read the initialparameters datagram to get pulse form and channel mode for
        # each channel. I don't think this datagram is available in all EK80 raw file
        # versions and I'm not sure if this is always the 2nd datagram so we'll fish
        # thru the first handful looking for it.
        for i in range(10):
            initial_param = fid.read(1)
            if initial_param['subtype'] == 'initialparameter':
                # this *is* the droid we're looking for
                break

        #  make sure we have an initial parameter datagram
        if initial_param['subtype'] == 'initialparameter':
            # We do, work through the channels and unpack the initial parameters values
            # Along the way, we convert pulse_form and channel_mode to human readable forms
            for chan in initial_param['initialparameter']:
                for field in EK80_INITIAL_PARAM_FIELDS:
                    try:
                        # pulse_form is converted to a string
                        if field == 'pulse_form':
                            if initial_param['initialparameter'][chan][field] == 1:
                                file_info['configuration'][chan][field] = 'FM'
                            else:
                                file_info['configuration'][chan][field] = 'CW'

                        # same with channel_mode
                        elif field == 'channel_mode':
                            if initial_param['initialparameter'][chan][field] == 1:
                                file_info['configuration'][chan][field] = 'passive'
                            else:
                                file_info['configuration'][chan][field] = 'active'

                        # this value doesn't need any conversion
                        else:
                            if field in initial_param['initialparameter'][chan]:
                                file_info['configuration'][chan][field] = \
                                        initial_param['initialparameter'][chan][field]
                    except:
                        # This field isn't in the datagram
                        file_info['configuration'][chan][field] = None

        else:
            # Couldn't find the initial parameter datagram
            file_info['configuration'][chan]['pulse_form'] = None
            file_info['configuration'][chan]['channel_mode'] = None

    else:
        # The older EK60 raw format has a simpler configuraiton datagram and does not
        # have the initialparameter datagram. We'll fish thru the first RAW0 datagrams and
        # grab similar info as is contained in the initialparameter datagram

        # Sanity check - if the header is not a configuration datagram, bail.
        if 'configuration' not in header:
            raise IOError('Unknown EK60 file format. Configuration header not found!')

        # Get the channels and create the configuration dictionary
        file_info['channels'] = list(header['configuration'].keys())
        file_info['configuration'] = {}

        # Set the application_name entry to None to indicate the file level attributes
        # have not been populated
        file_info['application_name'] = None

        #  create a dict to map channel number to channel ID - needed for EK60
        chan_num_map = {}
        chan_map_number = 1

        # loop thru the channels to extract configuration attributes for each channel
        for chan in file_info['channels']:
            #  create the configuration dict for this channel
            file_info['configuration'][chan] = {}

            # add this channel to the channel map
            chan_num_map[chan_map_number] = chan
            chan_map_number += 1

            # Check if we have parsed the attributes that are common across channels
            if file_info['application_name'] == None:
                # No, this must be the first channel we're parsing. Do the common attributes.
                for field in EK80_FILE_CONFIG_FIELDS:
                    try:
                        # For the EK60, use the mapping dict to map EK60 configuration fields
                        # to EK80 names.
                        file_info[field] = header['configuration'][chan][EK60_FILE_CONFIG_MAP[field]]
                    except:
                        # This field doesn't exist in EK60
                        file_info[field] = None

            # Add the transceiver configuration fields
            for field in EK80_XCVR_CONFIG_FIELDS:
                try:
                    file_info['configuration'][chan][field] = \
                            header['configuration'][chan][EK60_XCVR_CONFIG_MAP[field]]
                except:
                    file_info['configuration'][chan][field] = None
            # set the transceiver number, which for EK60 is the channel number
            file_info['configuration'][chan]['transceiver_number'] = chan_map_number
            
            # Add the transducer information
            file_info['configuration'][chan]['transducer'] = {}
            for field in EK80_XDCR_CONFIG_FIELDS:
                try:
                    if field == 'transducer_beam_type':
                        # Add the beam type name as we know it to the numerical type
                        beam_type = header['configuration'][chan][EK60_XDCR_CONFIG_MAP[field]]
                        # set the name based on the type
                        if beam_type == 0:
                            type_name = 'Single Beam : 1 sector'
                        elif beam_type == 1:
                            type_name = 'Split Beam : 4 sector'
                        elif beam_type == 17:
                            type_name = 'Split Beam : 3 sector'
                        elif beam_type in [49,65,81]:
                            type_name = 'Split Beam : 3 sector with center element'
                        else:
                            type_name = 'Split Beam : Unknown sector configuration.'
                            
                        file_info['configuration'][chan]['transducer'][field] = [beam_type, type_name]
                    else:
                        file_info['configuration'][chan]['transducer'][field] = \
                                header['configuration'][chan][EK60_XDCR_CONFIG_MAP[field]]
                except:
                    file_info['configuration'][chan]['transducer'][field] = None

            # Add in the assumed values for EK60 files
            file_info['configuration'][chan]['pulse_form'] = 'CW'
            file_info['configuration'][chan]['transceiver_type'] = 'GPT'
            file_info['configuration'][chan]['fpga_tx_firmware_ver'] = None
            file_info['configuration'][chan]['fpga_rx_firmware_ver'] = None

            # Parse out a few other fields from the channel ID
            try:
                id_parts = file_info['configuration'][chan]['channel_id'].split(' ')
                file_info['configuration'][chan]['transceiver_type'] = id_parts[0]
                file_info['configuration'][chan]['transceiver_name'] = id_parts[0] + ' ' + id_parts[3]
                file_info['configuration'][chan]['serial_number'] = id_parts[3]
                file_info['configuration'][chan]['ethernet_address'] = id_parts[3]
                file_info['configuration'][chan]['transducer']['transducer_name'] = id_parts[-1]
            except:
                # If parsing these fields fails, we just bail
                pass

        # Now read ahead looking for the first RAW0 datagram for each channel to
        # extract the remaining params from the RAW dataagrams.
        read_all_chans = [False] * len(file_info['channels'])
        while not np.all(read_all_chans):
            dgram = fid.read(1)
            if dgram['type'] == 'RAW0':
                # channels are mapped by number in RAW0 datagrams so map that back to our channel ID
                chan = chan_num_map[dgram['channel']]
                # populate the rest of the initial_parameters for this channel
                if dgram['transmit_mode'] == 1:
                    file_info['configuration'][chan]['channel_mode'] = 'passive'
                else:
                    file_info['configuration'][chan]['channel_mode'] = 'active'
                file_info['configuration'][chan]['pulse_duration'] = dgram['pulse_length']
                file_info['configuration'][chan]['sample_interval'] = dgram['sample_interval']
                file_info['configuration'][chan]['transmit_power'] = dgram['transmit_power']
                file_info['configuration'][chan]['sound_velocity'] = dgram['sound_velocity']
                file_info['configuration'][chan]['frequency'] = dgram['frequency']
                file_info['configuration'][chan]['pulse_duration'] = dgram['pulse_length']
                file_info['configuration'][chan]['slope'] = None

                # note that we have read the RAW datagram for this channel
                read_all_chans[dgram['channel'] - 1] = True

    #  close the idx file
    fid.close()

    # If we don't have or failed to read the .idx file, scan the .raw file for
    # the basic ping stats.
    if not has_idx:
        # There isn't an .idx file so we're going to do this the hard way. Read
        # the entire raw file, but don't store any data. This is faster than a
        # regular read, but slower than using the .idx file.
        data_object.append_raw(filename, power=False, angles=False, complex=False,
                nmea=False, motion=False)
    
        # Now extract some basic ping stats
        file_info['start_time'] = data_object.start_time
        file_info['end_time'] = data_object.end_time
        file_info['start_ping'] = data_object.start_ping
        file_info['end_ping'] = data_object.end_ping
        file_info['n_pings'] = data_object.end_ping - data_object.start_ping

    return file_info


def get_data_by_frequency(p_data_dict, frequency):
    '''get_data_by_frequency returns references to processed data objects contained
    within a dictionary keyed by channel ID. The echosounder.get_* methods return
    data in a dictionary keyed by channel ID. Sometimes you want references to these
    data by frequency. This function will do that for you.
    
        p_data_dict (dict): Set this to a dict, keyed by channel ID, containing
            the processed_data objects.

        frequency (float): Set this to the frequency you're looking for. If no channels
            match this frequency, None is returned. If one channel matches, a
            reference to that channel will be returned. If multiple channels match,
            a list of references will be returned.

            Note that with FM data (Sv(f), TS(f)), the mean frequency is used for
            the match.

    '''

    freq_matched_objs = None

    # Loop thru the processed_data objects, checking their frequencies
    for chan in p_data_dict:
        if np.mean(p_data_dict[chan].frequency) == frequency:
            # We have a match, assign it based on what has already been assigned
            if freq_matched_objs is None:
                # This is the first instance
                freq_matched_objs = p_data_dict[chan]
            elif isinstance(freq_matched_objs, list):
                # We already have multiple matches, so add this to the list
                freq_matched_objs.append(p_data_dict[chan])
            else:
                # This is the second match, create the list containing the
                # first and second references.
                freq_matched_objs = [freq_matched_objs, p_data_dict[chan]]

    return freq_matched_objs


def apply_boundary_exclusions(data_object, exclude_below_line='xyz', exclude_above_line=None,
        bottom_offset=0, exclude_val=np.nan):
    '''
    Default is to apply the bottom line associated with the channel ('xyz').
    '''
    data_object_new = copy.deepcopy(data_object)

    if not isinstance(data_object_new, dict):
        raise TypeError('Expected a dictionary of processed_data objects (e.g., Sv)')
        
    #  apply surface and boundary 
    for channel in data_object_new:
        if np.all(data_object_new[channel].cal_parms['channel_mode'] == 0): #active channel
            data_object_new[channel] = apply_lines(data_object_new[channel],
                    exclude_below_line=exclude_below_line,exclude_above_line=exclude_above_line,
                    bottom_offset=bottom_offset, exclude_val=exclude_val)

    return data_object_new


def apply_lines(data_object,exclude_below_line='xyz',exclude_above_line=None,
        bottom_offset=0, exclude_val=np.nan):
    '''
    Applies an exclusion mask to a processed data object
    data are returned as
    '''
    exclusion_mask = mask.mask(like=data_object, value=False)

    # apply exclude above and below lines if provided
    if exclude_above_line is not None:
        if isinstance(exclude_above_line, int) | isinstance(exclude_above_line, float):
            exclude_above_line = line.line(ping_time=data_object.ping_time, data=exclude_above_line)
        exclusion_mask.apply_above_line(exclude_above_line, value=True)

    if exclude_below_line is not None:
        if exclude_below_line == 'xyz':
            if hasattr(data_object, 'bottom_line'):
                exclusion_mask.apply_below_line(data_object.bottom_line+bottom_offset, value=True)
            else:
                warnings.warn('No bottom line found in the data for channel %s' % data_object.channel_id)

        elif isinstance(exclude_below_line, int) | isinstance(exclude_below_line, float):
            exclude_below_line = line.line(ping_time=data_object.ping_time, data=exclude_below_line)
            exclusion_mask.apply_below_line(exclude_below_line, value=True)

    data_object[exclusion_mask] = exclude_val  # set masked values to np.nan or -9999

    return data_object


def noise_correct(data_object, SNR_threshold=None, remove_passive=True,
        keep_noise_Sv=True, exclude_val=-999, thresh=20, min_range=5,
        run_mean_weights=np.array([.25,.5,.25])):

    data_object = copy.deepcopy(data_object)
    remove_channels = []

    for channel in data_object:
        if np.all(data_object[channel].cal_parms['channel_mode'] == 0):
            passive_channel = _find_matching_channel(data_object, channel)
            if passive_channel is None:
                warnings.warn('Unable to find matching passive channel for active channel ' + channel +
                        '. This channel will not be noise corrected.')
                continue
            passive_channel_power = data_object[passive_channel].to_power()
            passive_channel_power = noise.noise_from_passive(passive_channel_power,thresh=thresh,
                    min_range=min_range,run_mean_weights=run_mean_weights)

            if passive_channel_power.noise_P.ndim == 2:
                noise_power = np.zeros((passive_channel_power.noise_P.shape[0],
                        data_object[channel].ping_time.shape[0]),
                        dtype=passive_channel_power.noise_P.dtype)
                for i,n in enumerate(passive_channel_power.noise_P):
                    noise_power[i] = np.interp(data_object[channel].ping_time.astype('d'),
                            passive_channel_power.ping_time.astype('d'), n)
            else:
                noise_power = np.interp(data_object[channel].ping_time.astype('d'),
                        passive_channel_power.ping_time.astype('d'), passive_channel_power.noise_P)

            data_object[channel].add_object_attribute('noise_power',noise_power)
            noise.Sv_noise_from_estimate(data_object[channel])

            data_object[channel] = noise.noise_correct(data_object[channel])

            if SNR_threshold is not None:
                data_object[channel]=noise.SNR_threshold(data_object[channel], SNR_threshold,
                        exclude_val=exclude_val)

            if remove_passive:
                remove_channels.append(passive_channel)
            if keep_noise_Sv is False:
                del data_object[channel].noise_Sv

    if remove_passive:
        for k in remove_channels:
            data_object.pop(k)

    return data_object


def add_noise_estimate(data_object, frequencies=None, channel_ids=None):
    '''
    Adds noise estimate to an Sv processed data dictionary, keyed by channel ID.
    '''
    pass

    #for channel in data_object:
        # if it's an active channel, get the matching passive channel
        # convert the passive channel to power
        # calculate the noise estimate from the passive channel
        # add the noise estimate (in power) to the active channel
        # TEMP: build a noise estimate that matches the size of the active channel and convert to Sv


def _filter_channel(chan, raw_obj, channels, frequencies,data_type):

    return_chan = False
    if channels is None and frequencies is None:
        return_chan = True
    elif channels is None and raw_obj.configuration[0]['transducer_frequency'] in frequencies:
        return_chan = True
    elif frequencies is None and chan in channels:
        return_chan = True
    elif chan in channels and raw_obj.configuration[0]['transducer_frequency'] in frequencies:
        return_chan = True

    if (data_type=='Svf') and (hasattr(raw_obj,'complex') is False):
        # If we don't have complex we can't calculate Svf
        return_chan = False 

    return return_chan


def _check_filetype(filename):

    # Read in the file header, this value can change if additional
    # instruments are introduced with larger headers.
    fh = open(filename, "rb")
    header = fh.read(8)
    fh.close()

    # Return the file type based on the header
    if header[4:8]==b'CON0':
        # Simrad EK60 style raw files start  with 4 bytes for the size then C O N 0
        return SIMRAD_EK60

    elif header[4:8]==b'XML0':
        # Simrad EK80 style raw files start with 4 bytes for the size then X M L 0
        return SIMRAD_EK80

    else:
       return -1


def _find_matching_channel(data_obj,channel_id): # update to deal with either raw or processed objects, .data_type
        '''
        Simple approach to finding matching channel based on pre-defined attributes. Acts a
        a helper function for the get_calibration_from_xml function to find the matching channels
        via _compare_pulse function.
        '''

        if isinstance(data_obj, dict): # we're working with a processed data dictionary
            matching = [s for s in data_obj.keys() if channel_id[:-2] in s and s!=channel_id]
            obj_type = 'processed'
        elif hasattr(data_obj,'raw_data'): # raw EK data object
            matching = [s for s in data_obj.channel_ids if channel_id[:-2] in s and s!=channel_id]
            obj_type = 'raw'
        else:
            raise UnknownFormatError('Unknown data object format. Expected a raw or processed data dictionary.')

        # If there are any other channels with matching transciever names, check if the other attributes match
        if matching:
            for ch in matching:
                if obj_type == 'processed':
                    all_match = _compare_pulse(data_obj[channel_id],data_obj[ch],raw=False)
                elif obj_type == 'raw':
                    all_match = _compare_pulse(data_obj.get_channel_data()[channel_id][0],
                            data_obj.get_channel_data()[ch][0])
                # If all attributes match, return the channel
                if all_match:
                    return ch
        # If no matching channel is found, return None
        else:
            return None


def _compare_pulse(primary_obj,secondary_obj, raw=True):
    '''
    Compares the pulse attributes between two data objects (raw, processed, calibration)
    and returns True if all attributes match, False if any do not match.

    primary_obj (object): raw or processed data object

    secondary_obj (object): raw, processed, or calibration data object
    '''

    all_match = True

    if raw:
        #  set the list of attributes to compare based on pulse form
        if primary_obj.is_fm():
            pulse_attrs = ['pulse_form','frequency_start','frequency_end',
                    'pulse_duration','transmit_power']
        else:
            pulse_attrs = ['pulse_form','frequency','pulse_duration','transmit_power']

        # Check each attribute. Assume they match until proven otherwise
        for attr in pulse_attrs:
            # Check if the attribute exists in both channels
            if hasattr(secondary_obj,attr):
                # Check if the attribute values match. Due to a bug in the EK80 software,
                # the end frequency in the XML calibration file may be 1 Hz off from the
                # end frequency in the raw file. Because of this, the frequency_end value
                # from the XML file is rounded.
                if attr != 'frequency_end':
                    if (np.unique(getattr(primary_obj,attr))[0] !=
                        np.unique(getattr(secondary_obj,attr))[0]):
                        all_match = False
                else:
                    #  this is frequency_end, round the XML cal object value
                    if (np.unique(getattr(primary_obj,attr))[0] !=
                        round(np.unique(getattr(secondary_obj,attr))[0],-1)):
                        all_match = False
            else:
                #  this attribute is not in the secondary object
                all_match = False
    else:
        #  this is a processed data object
        
        #  first check if the frequencies match
        if primary_obj.frequency.all() != secondary_obj.frequency.all():
            #  they do not
            all_match = False
        else:
            # Frequencies match. Compare the pulse attributes directly
            pulse_attrs = ['pulse_form', 'pulse_duration', 'transmit_power']
            for attr in pulse_attrs:
                if (np.unique(primary_obj.cal_parms[attr])[0] !=
                    np.unique(secondary_obj.cal_parms[attr])[0]):
                    all_match = False
    return all_match


class UnknownFormatError(Exception):
    pass
