'''
Resample Test

Gridding Notes:

The grid edges and centers generated by echoview when resamping by time interval
don't totally make sense to me. For example, in DY2002_EK80-D20200220-T070830.raw,
first ping starts at 07:08:30.012. In EV 16, when resampling by 5 minute intervals,
the first interval center is at 07:07:30.00 which is about a minute BEFORE the first
ping? The first interval center in Echolab is 07:10:57.534 which lands somewhere
between pings 67 and 68. This makes sense as the first interval has 135 pings.



'''
import numpy as np
import matplotlib.pyplot as plt
from timeit import default_timer as timer
from echolab2.instruments import echosounder
from echolab2.processing import processed_data, grid
from echolab2.plotting.matplotlib import echogram


#  specify the difference echogram's threshold.
diff_threshold = [-0.1, 0.1]

#  specify the color table used for the difference echograms
diff_cmap='PuOr'

test_array_size = (10,400)
data_block_shape = (5,20)
data_block_values = (-45,-90)
sample_thickness = 0.25


resample_v_size = 100
resample_v_axis = 'sample'
resample_h_size = 5
resample_h_axis = 'ping_number'


Sv38_orig = processed_data.create_test_data(test_array_size[0], test_array_size[1],
        block_shape=data_block_shape, block_values=data_block_values, data_type='Sv', 
        jitter_time=True, jitter_range=(0,250), sample_thickness=sample_thickness, range_start=0)


# resampling happens in place, so we need to make copies of the original
# data for each method we want to test.
Sv38_bf = Sv38_orig.copy()
Sv38_area = Sv38_orig.copy()
Sv38_center = Sv38_orig.copy()


start = timer()
print("Brute Force center weighted resample...")
Sv38_bf.brute_force_resample(resample_v_size, resample_h_size, v_axis=resample_v_axis, h_axis=resample_h_axis)
elapsed_bf = timer() - start
print("BF Resample Time: ", elapsed_bf)

start = timer()
print("Area weighted resample...")
Sv38_area.resample_by_axes(resample_v_size, resample_h_size, v_axis=resample_v_axis, h_axis=resample_h_axis,
            method='area_weighted')
elapsed_rsw = timer() - start
print("Area weighted Resample Time: ", elapsed_rsw)

start = timer()
print("Center weighted resample...")
Sv38_center.resample_by_axes(resample_v_size, resample_h_size, v_axis=resample_v_axis, h_axis=resample_h_axis,
            method='center_weighted')
elapsed_rsw = timer() - start
print("Center weighted Resample Time: ", elapsed_rsw)



#  show the Echolab and Echoview echograms
fig = plt.figure()
eg = echogram.Echogram(fig, Sv38_orig, threshold=[-70,-34], y_axis='sample', x_axis='ping_number')
eg.add_colorbar(fig)
eg.axes.set_title("Echolab2 Original Sv" + str(Sv38_orig.frequency) + " kHz")

Sv38_area.resample_dest_interval_edges
Sv38_area.resample_source_interval_edges

print()

# plot the resampling grid on top of the original data.
resamp_grid = grid.grid(interval_length=resample_h_size, interval_axis=resample_h_axis,
        layer_thickness=resample_v_size, layer_axis='sample')
resamp_grid.update(Sv38_orig)
eg.set_grid(resamp_grid)


fig = plt.figure()
eg = echogram.Echogram(fig, Sv38_bf, threshold=[-70,-34])
eg.add_colorbar(fig)
eg.axes.set_title("Echolab2 Brute Force Resample" + str(Sv38_bf.frequency) + " kHz")

fig = plt.figure()
eg = echogram.Echogram(fig, Sv38_area, threshold=[-70,-34])
eg.add_colorbar(fig)
eg.axes.set_title("Echolab2 Area Weighted Resample" + str(Sv38_area.frequency) + " kHz")

fig = plt.figure()
eg = echogram.Echogram(fig, Sv38_center, threshold=[-70,-34])
eg.add_colorbar(fig)
eg.axes.set_title("Echolab2 Center Weighted Resample" + str(Sv38_center.frequency) + " kHz")


#  plot the differences
diff = Sv38_area - Sv38_bf
fig = plt.figure()
eg = echogram.Echogram(fig, diff, threshold=diff_threshold, cmap=diff_cmap)
eg.add_colorbar(fig)
eg.axes.set_title("Area weighted Sv - Brute force Sv " +
        str(Sv38_orig.frequency) + " kHz")

diff = Sv38_center - Sv38_bf
fig = plt.figure()
eg = echogram.Echogram(fig, diff, threshold=diff_threshold, cmap=diff_cmap)
eg.add_colorbar(fig)
eg.axes.set_title("Center weighted Sv - Brute force Sv " +
        str(Sv38_orig.frequency) + " kHz")

diff = Sv38_area - Sv38_center
fig = plt.figure()
eg = echogram.Echogram(fig, diff, threshold=diff_threshold, cmap=diff_cmap)
eg.add_colorbar(fig)
eg.axes.set_title("Area weighted Sv - Center weighted Sv " +
        str(Sv38_orig.frequency) + " kHz")


# Show our figures.
plt.show()

print("Done.")






