# -*- coding: utf-8 -*-
"""my_first_echogram.py

This script demonstrates using the echosounder module to reading a raw file
containing CW data and plot Sv echograms.

The echosounder module provides a simplified interface for reading raw data
generated by EK60, EK80, and similar instruments. Due to the wide variety of
instruments that utilize the Simrad "raw" data format and their many configuration
options, pyEcholab's classes for working with these data are complex. The
echosounder module makes a few assumptions that are applicable to most use
cases that significantly reduces this complexity.

The major assumption made by the echosounder class is that when reading multiple
files in one call, those files will contain sample data of the same type (complex,
power only, power+angle, angles only.) Further, it is STRONGLY ENCOURAGED that
when reading multiple files that the files share the same transmit settings
(power, pulse form, pulse length, etc.) to ensure that the calibration parameters
are applied correctly across all pings. 



"""

import matplotlib.pyplot as plt
from echolab2.instruments import echosounder
from echolab2.plotting.matplotlib import echogram


#  specify the raw file to read. You can provide a string specifying the
#  full path to the data file or a list of strings if you want to read
#  multiple files at the same time.


# Specify the full path to the raw file to read. You can specify a single file or
# a list of files to read. When reading multiple files, the files should contain
# the same data type and share the same transmit settings for all matching channels.
# In this example, we will read a single EK60 raw file. 
rawfile='C:/EK Test Data/EK60/DY1807/raw/DY1807_EK60-D20180609-T122526.raw'


#  use the echosounder module to read the data. The Echosounder module provides
#  a simple interface for reading and extracting data from Simrad .raw files.
#  It will read the specified raw file(s) and attempt to read their associated
#  bottom detection files. It is assumed the .xyz or .bot files will be colocated
#  with the .raw files. echosounder.read() will return either an EK60 or EK80
#  object depending on the format of the data that was read.
print("Reading .raw data: " + rawfile)
ek_data = echosounder.read(rawfile)

#  print some information about the data we just read
print("Raw data object info:")
print(ek_data)

#  get calibration objects for the data.  echosounder.get_calibration_from_raw()
#  will return a dict, keyed by channel ID, each containing a calibration object
#  populated using the data from the raw data. Since you can't always trust the
#  embedded calibration parameters, ideally you will have calibration data in the
#  form of a Simrad calibration .xml file generated by EK80 or an Echoview
#  .ecs file. The echosounder module has functions for getting calibration params
#  from these files as well.

cal_objects = echosounder.get_calibration_from_raw(ek_data)
print(cal_objects)

#  While we will not do it here, you can modify the calibration values as needed
#  if the values you want to use were not recorded in the .raw file. For example,
#  the sound speed recorded in the file is not the sound speed you measured during
#  data collection.

#  now get Sv data. We pass the EK data object which contains the raw sounder data,
#  our dictionary of calibration objects, and we set return_depth to True to return
#  data on a depth grid. get_Sv() will return a dictionary, keyed by channel ID,
#  containing the raw sample data converted to Sv using the parameters specified in
#  the calibration object. The data are contained in a echolab processed_data object
#  that has many other useful attributes
Sv_data = echosounder.get_Sv(ek_data, calibration=cal_objects)

#  iterate thru the channels contains in Sv_data and plot
for channel_id in Sv_data:

    #  print some info about this processed data object
    print("Processed data object info:")
    print(Sv_data[channel_id])
    print()

    #  create a figure to plot our echogram in
    fig = plt.figure()

    #  create an echogram
    eg = echogram.Echogram(fig, Sv_data[channel_id], threshold=[-70,-34])

    #  add the bottom line if we have one
    if hasattr(Sv_data[channel_id], 'bottom_line'):
        eg.plot_line(Sv_data[channel_id].bottom_line, color=[1.0, 0.8, 0], linewidth=1.5)

    #  and a color bar
    eg.add_colorbar(fig)

    # and title
    eg.axes.set_title("Sv " + str(channel_id))


# Show our figures
plt.show()

print()


