# -*- coding: utf-8 -*-
"""plot_anglogram.py

This script demonstrates using the echosounder module to reading a raw file
containing CW data and plot the angle data as anglograms.
"""

import matplotlib.pyplot as plt
from echolab2.instruments import echosounder
from echolab2.plotting.matplotlib import echogram


# Specify the full path to the raw file to read. You can specify a single file or
# a list of files to read. When reading multiple files, the files should contain
# the same data type and share the same transmit settings for all matching channels.
# In this example, we will read a single EK80 raw file. 
rawfile='./data/EK80/cw/DY2003/raw/DY2003_EK80-D20200312-T184159.raw'


#  use the echosounder module to read the data. The Echosounder module provides
#  a simple interface for reading and extracting data from Simrad .raw files.
#  It will read the specified raw file(s) and attempt to read their associated
#  bottom detection files. It is assumed the .xyz or .bot files will be colocated
#  with the .raw files. echosounder.read() will return either an EK60 or EK80
#  object depending on the format of the data that was read.
print("Reading .raw data: " + rawfile)
ek_data = echosounder.read(rawfile)

#  print some information about the data we just read
print("Raw data object info:")
print(ek_data)

#  get calibration objects for the data. Ideally you will have calibration data
#  in the form of a Simrad calibration .xml file generated by EK80 or an Echoview
#  .ecs file. The echosounder module has functions for getting calibration params
#  from these files. For this example, we will use the calibration values from the
#  raw data.
cal_objects = echosounder.get_calibration_from_raw(ek_data)

#  now get the angle data. Pass the EK data object which contains the raw sounder data 
#  and our dictionary of calibration objects to the echosounder.get_angles() function. 
#  It will return a dictionary, keyed by channel ID, containing (alongship, athwartship)
#  tuples of processed_data objects. The raw electrical angles are converted to physical
#  angles using the parameters specified in the calibration object.
angle_data = echosounder.get_angles(ek_data, calibration=cal_objects, return_depth=True)


#  get a colormap for our anglograms
angle_cmap = plt.get_cmap('plasma')

#  iterate thru the channels contained in angle_data and plot
for channel_id in angle_data:

    #  print some info about this processed data object
    print("Alongship Processed data object info:")
    print(angle_data[channel_id][0])
    print("Athwartship Processed data object info:")
    print(angle_data[channel_id][1])
    print()

    #  create a figure to plot our anglograms in
    fig = plt.figure()
    # Set some properties for the sub plot layout.
    plt.subplots_adjust(left=0.11, bottom=0.1, right=0.98, top=.93, wspace=None,
                hspace=0.9)

    # Add the alongship angles as a subplot
    ax_1 = fig.add_subplot(2, 1, 1)
    eg = echogram.Echogram(ax_1, angle_data[channel_id][0], cmap=angle_cmap)
    ax_1.set_title("Alongship angles " + str(channel_id))

    #  add the bottom line if we have one
    if hasattr(angle_data[channel_id][0], 'bottom_line'):
        eg.plot_line(angle_data[channel_id][0].bottom_line, color=[0, 0.8, 0],
                linewidth=1.5)
        
    #  and a color bar
    eg.add_colorbar(fig, 'Angle')


    # Add the athwartship angles as a subplot
    ax_2 = fig.add_subplot(2, 1, 2)
    eg = echogram.Echogram(ax_2, angle_data[channel_id][1], cmap=angle_cmap)
    ax_2.set_title("Athwartship angles " + str(channel_id))

    #  add the bottom line if we have one (note that with angle data, the
    #  data attributes like bottom_line, latitude, longitude, etc. are replicated
    #  for both the alongship and athwartship objects we can grab the bottom
    #  from either object.)
    if hasattr(angle_data[channel_id][0], 'bottom_line'):
        eg.plot_line(angle_data[channel_id][0].bottom_line, color=[0, 0.8, 0],
                linewidth=1.5)

    #  and a color bar
    eg.add_colorbar(fig, 'Angle')

# Show our figures
plt.show()

print()
