# -*- coding: utf-8 -*-
"""An example of reading a sounder detected bottom .xyz file.

This script is an echolab2 example demonstrating how to read .xyz files
generated by the EK80 system. .xyz files store bottom detection data
by channel ID.

If you are simply looking to read data, transform it to Sv, Sp, or
power, and work with the sounder detected bottom line, you should use the
echosounder module's get_* methods. These methods will return processed
data with the bottom line included as the "bottom_line" attribute.

This example is intended to demonstrate how to do things the hard way.
(But not the *really* hard way. It still leverages the echosounder module
to read the raw and xyz data files.)


Definitions:

  The following attribute names are used in this example and they are
  defined here for clarity.

    transducer_offset is the vertical position of the transducer WITHOUT
    heave applied. It is a combination of the transducer_z_offset and the
    transducer_depth (EK60) or drop_keel_offset or water_level_draft (EK80)

    heave is the dynamic vertical displacement of your sampling platform
    provided by your platform's AHRS/IMU and as recorded by the EK60/EK80.

    transducer_draft is the vertical position of the transducer WITH heave
    applied:

        transducer_draft = transducer_offset + heave


The key takeaways:

 1) Bottom data must be read *after* its corresponding raw data. Bottom
    data will be matched to an existing "ping". If that ping doesn't
    exist, the bottom data value will be discarded.

 2) Keep your vertical axes consistent. Bottom detections are always
    returned as depth with heave correction applied (if heave data were
    available at the time of recording.) You must adjust the bottom line
    accordingly depending on the vertical axis of your sample data and
    whether or not heave correction has been applied to it. This can be
    done using the transducer_draft attribute of the bottom detection
    lines and the transducer_offset attribute of your processed_data
    object.

 3) If you change any parameters in the calibration object you must
    pass it using the "calibration" keyword when "getting" data from
    a raw_data object. In no calibration is provided, those methods
    will use the parameters from the .raw file.

"""

from matplotlib.pyplot import figure, show
from echolab2.instruments import echosounder
from echolab2.processing import line
from echolab2.plotting.matplotlib import echogram



#  set the path to a xyz file to read
xyz_38_file = 'C:/EK Test Data/EK80/DY2308/cw/DY2308_EK80-D20230702-T181248-ES38-7 Serial No  324 - Narrow.XYZ'


#  Set the path to a raw file to read. This is used for the part of the example
#  where we use the echosounder module to read the raw data and the corresponding
#  bottom files. The bottom files must be colocated with the raw data.
rawfile = 'C:/EK Test Data/EK80/DY2308/cw/DY2308_EK80-D20230702-T181248.raw'



#  if you simply want to read an .xyz file and do not care about the sample
#  data, you can use the echolab2.processing.line class to read the data and
#  return a line object containing the data. This will include the lat/lon,
#  sounder detected bottom, and the transducer draft (with heave applied, if
#  applicable.)
#
#  it is important to remember that the depths stored in the .xyz file are
#  computed using the sound speed that was configured in the EK software when
#  the data were recorded and they will have heave correction applied if heave
#  was input into the system. When reading .xyz files directly like this, you
#  are responsible for correcting the depths if the actual sound speed was
#  different from the configured sound speed.
print('reading the XYZ file...')
bottom_line_38 = line.read_xyz(xyz_38_file)
print(bottom_line_38)
'''
<class 'echolab2.processing.line.line'> at 0x22f7f01c850
                 line name: xyz_line
             n data points: 150
                start time: 2023-06-10T16:19:15.790
                  end time: 2023-06-10T16:21:51.590
         object attributes: ping_time (150)
                            latitude (150)
                            longitude (150)
                            transducer_draft (150)
'''



#  if you want to read the .xyz file and work with the sample data, then you
#  start by reading the .raw file. We'll use the echosounder module to read
#  the raw file as it will automagically read the bottom files if they are
#  present in the same directory.
print('Reading ' + rawfile + '...')
echosounder_data = echosounder.read(rawfile)

#  print some basic info about the data we read
print(echosounder_data)
'''
<class 'echolab2.instruments.EK80.EK80'> at 0x1e040e88810
    EK80 object contains data from 5 channels:
        WBT 998500-15 ES18_ES :: power/angle (1784, 24197)
        WBT 978217-15 ES38-7_ES :: power/angle (1784, 33875)
        WBT 978213-15 ES70-7C_ES :: power/angle (1784, 28229)
        WBT 976714-15 ES120-7C_ES :: power/angle (1784, 28229)
        WBT 978208-15 ES200-7C_ES :: power/angle (1784, 33875)
    data start time: 2023-07-02T18:12:48.996
      data end time: 2023-07-02T18:45:36.281
    number of pings: 1784
'''

#  most users would call one of the echosounder_data.get_* methods to get a processed
#  data object that contains the transformed sample data as well as bottom line. In this
#  example we'll do this all the hard way.

#  get the raw data for the 38 and 120 channels - we know that we have read a single EK80
#  file that contains data of a single data type so we know there will only be one
#  raw_data object in the list returned by get_channel_data() so we'll unpack that here.
#  If your example file contains multiple channels at 38 or 120 kHz or you read multiple
#  files containing different data types (complex, power+angle, power only, angle only)
#  there will be multiple raw_data objects per frequency and you will need to handle
#  that yourself.
raw_data = echosounder_data.get_channel_data(frequencies=[38000, 120000])
raw_data_38 = raw_data[38000][0]
raw_data_120 = raw_data[120000][0]


#  Create calibration objects for each channel. Unless you yourself collected the
#  data you are working with, you shouldn't trust the calibration parameters contained
#  within the raw data file for quantitative work. But, since this is just an example,
#  we are going to ignore best practices and use the cal values contained within
#  the raw file. We call the raw_data.get_calibration() method to extract the cal
#  params from the raw data and return calibration objects
cal_38 = raw_data_38.get_calibration()
cal_120 = raw_data_120.get_calibration()
print(cal_38)
'''
<class 'echolab2.instruments.EK80.ek80_calibration'> at 0x161e4f807d0
                         frequency :: array 150 :: First value: 38000.0
                   frequency_start :: No value set
                     frequency_end :: No value set
                    transmit_power :: scalar :: Value: 2000.0
                    pulse_duration :: scalar :: Value: 0.000512
                     sample_offset :: scalar :: Value: 0
                      channel_mode :: scalar :: Value: 0
                        pulse_form :: scalar :: Value: 0
                   sample_interval :: scalar :: Value: 2e-05
                             slope :: scalar :: Value: 0.205592
                      sample_count :: scalar :: Value: 34106
                 pulse_duration_fm :: array 5 :: First value: 0.000512
                              gain :: array 150 :: First value: 25.5
                     sa_correction :: array 150 :: First value: 0.0
             equivalent_beam_angle :: array 150 :: First value: -20.7
       angle_sensitivity_alongship :: array 150 :: First value: 18.0
     angle_sensitivity_athwartship :: array 150 :: First value: 18.0
            angle_offset_alongship :: array 150 :: First value: -0.03
          angle_offset_athwartship :: array 150 :: First value: 0.07
              beam_width_alongship :: array 150 :: First value: 6.42
            beam_width_athwartship :: array 150 :: First value: 6.54
 directivity_drop_at_2x_beam_width :: scalar :: Value: 0.0
               transducer_offset_x :: scalar :: Value: 0.0
               transducer_offset_y :: scalar :: Value: 0.0
               transducer_offset_z :: scalar :: Value: 0.0
                transducer_alpha_x :: scalar :: Value: 0.0
                transducer_alpha_y :: scalar :: Value: 0.0
                transducer_alpha_z :: scalar :: Value: 0.0
                   transducer_name :: scalar :: Value: ES38-7
          hw_channel_configuration :: scalar :: Value: 15
               rx_sample_frequency :: array 150 :: First value: 1500000.0
                         time_bias :: scalar :: Value: 0
               transducer_mounting :: scalar :: Value: DropKeel
                  transceiver_type :: scalar :: Value: WBT
                         impedance :: scalar :: Value: 5400
              transducer_frequency :: scalar :: Value: 38000.0
      transducer_frequency_minimum :: scalar :: Value: 34000.0
      transducer_frequency_maximum :: scalar :: Value: 45000.0
              transducer_beam_type :: scalar :: Value: 65
                             depth :: scalar :: Value: 70.0
                           acidity :: scalar :: Value: 8.0
                          salinity :: scalar :: Value: 33.0
                       sound_speed :: scalar :: Value: 1466.0
                       temperature :: scalar :: Value: 4.0
                          latitude :: scalar :: Value: 45.0
            transducer_sound_speed :: scalar :: Value: [1466.0]
            sound_velocity_profile :: array 4 :: First value: 1.0
                  drop_keel_offset :: scalar :: Value: 5.3
                 water_level_draft :: scalar :: Value: 0.0
'''

print(cal_120)
'''
<class 'echolab2.instruments.EK80.ek80_calibration'> at 0x161e51801d0
                         frequency :: array 150 :: First value: 120000.0
                   frequency_start :: No value set
                     frequency_end :: No value set
                    transmit_power :: scalar :: Value: 250.0
                    pulse_duration :: scalar :: Value: 0.000512
                     sample_offset :: scalar :: Value: 0
                      channel_mode :: scalar :: Value: 0
                        pulse_form :: scalar :: Value: 0
                   sample_interval :: scalar :: Value: 2.4e-05
                             slope :: scalar :: Value: 0.0325521
                      sample_count :: scalar :: Value: 28422
                 pulse_duration_fm :: array 5 :: First value: 0.000512
                              gain :: array 150 :: First value: 27.0
                     sa_correction :: array 150 :: First value: 0.0
             equivalent_beam_angle :: array 150 :: First value: -20.7
       angle_sensitivity_alongship :: array 150 :: First value: 23.0
     angle_sensitivity_athwartship :: array 150 :: First value: 23.0
            angle_offset_alongship :: array 150 :: First value: -0.01
          angle_offset_athwartship :: array 150 :: First value: -0.06
              beam_width_alongship :: array 150 :: First value: 6.57
            beam_width_athwartship :: array 150 :: First value: 6.54
 directivity_drop_at_2x_beam_width :: scalar :: Value: 0.0
               transducer_offset_x :: scalar :: Value: 0.0
               transducer_offset_y :: scalar :: Value: 0.0
               transducer_offset_z :: scalar :: Value: 0.0
                transducer_alpha_x :: scalar :: Value: 0.0
                transducer_alpha_y :: scalar :: Value: 0.0
                transducer_alpha_z :: scalar :: Value: 0.0
                   transducer_name :: scalar :: Value: ES120-7C
          hw_channel_configuration :: scalar :: Value: 15
               rx_sample_frequency :: array 150 :: First value: 1500000.0
                         time_bias :: scalar :: Value: 0
               transducer_mounting :: scalar :: Value: DropKeel
                  transceiver_type :: scalar :: Value: WBT
                         impedance :: scalar :: Value: 5400
              transducer_frequency :: scalar :: Value: 120000.0
      transducer_frequency_minimum :: scalar :: Value: 90000.0
      transducer_frequency_maximum :: scalar :: Value: 170000.0
              transducer_beam_type :: scalar :: Value: 1
                             depth :: scalar :: Value: 70.0
                           acidity :: scalar :: Value: 8.0
                          salinity :: scalar :: Value: 33.0
                       sound_speed :: scalar :: Value: 1466.0
                       temperature :: scalar :: Value: 4.0
                          latitude :: scalar :: Value: 45.0
            transducer_sound_speed :: scalar :: Value: [1466.0]
            sound_velocity_profile :: array 4 :: First value: 1.0
                  drop_keel_offset :: scalar :: Value: 5.3
                 water_level_draft :: scalar :: Value: 0.0
'''


# For fun, we'll provide our own sound speed. You can either provide
# calibration parameters as a scalar, in which case the value will
# be used for all pings or you can provide a ping-by-ping value.
# Here we'll just set a single value.
cal_38.sound_velocity = 1475
cal_120.sound_velocity = 1475

# Get Sv data on a range grid.
Sv_38_range = raw_data_38.get_Sv(calibration=cal_38)
Sv_120_range = raw_data_120.get_Sv(calibration=cal_120)

# Get a copy of our range based data and apply heave correction.
# You must pass a motion_data object to the processed_data.heave_correct()
# method.
# NOTE - applying heave correction will convert the processed_data
#        object's vertical axis from range to depth.
Sv_38_depth = Sv_38_range.copy()
Sv_38_depth.heave_correct(echosounder_data.motion_data)
Sv_120_depth = Sv_120_range.copy()
Sv_120_depth.heave_correct(echosounder_data.motion_data)

# Now get the bottom detection data - raw_data.get_bottom() returns
# an echolab2 line object representing the bottom detections.
#
# Since we have modified the calibration object (by setting the
# sound speed) we must pass it to the get_bottom method to ensure
# the new sound speed value is used. The get_bottom() method will
# adjust the data values based on the difference between the recorded
# sound speed and the value in the calibration object.
#
# IMPORTANT! - Bottom detections are *always* returned as depth with
#              heave corrections applied (if data were available at the
#              time of recording.)

bottom_38_as_depth_w_heave = raw_data_38.get_bottom(calibration=cal_38)
bottom_120_as_depth_w_heave = raw_data_120.get_bottom(calibration=cal_120)

# Set the color of our DEPTH_WITH_HEAVE lines to yellow
bottom_38_as_depth_w_heave.color = [1, 1, 0]
bottom_120_as_depth_w_heave.color = [1, 1, 0]

# We'll first display the data on a range grid. The vertical axis for the
# Sv data is already in range, but as stated above, the bottom detection
# data read from the .bot file will have transducer offset and heave (if
# available) applied. We first have to back those out from the bottom
# lines.
#
# In echolab transducer_draft = transducer_offset + heave
#
# When we subtract the transducer_draft we remove both the offset and heave
# which results in a line in RANGE. For convenience the transducer_draft
# data is included as attributes of the line object by the get_bottom() method:
bottom_38_as_range = bottom_38_as_depth_w_heave - \
        bottom_38_as_depth_w_heave.transducer_draft
bottom_120_as_range = bottom_120_as_depth_w_heave - \
        bottom_120_as_depth_w_heave.transducer_draft

# Set the color of our RANGE lines to purple
bottom_38_as_range.color = [1, 0, 1]
bottom_120_as_range.color = [1, 0, 1]

# Create matplotlib echograms and plot the data on a RANGE grid
# Plot the bottom detections as range as a purple line
# We also plot the detected bottom line that includes heave as a yellow line
fig_38 = figure()
eg = echogram.Echogram(fig_38, Sv_38_range, threshold=[-70, -34], cmap='viridis')
eg.axes.set_title("38 kHz on Range grid")
eg.plot_line(bottom_38_as_range, linewidth=2)
eg.plot_line(bottom_38_as_depth_w_heave, linewidth=2)

fig_120 = figure()
eg = echogram.Echogram(fig_120, Sv_120_range, threshold=[-70, -34], cmap='viridis')
eg.axes.set_title("120 kHz on Range grid")
eg.plot_line(bottom_120_as_range, linewidth=2)
eg.plot_line(bottom_120_as_depth_w_heave, linewidth=2)


# Now plot the data on a DEPTH grid.

# Next we have to back out the heave from the bottom line. Line
# objects contain the transducer_draft attribute which is a combination
# of transducer_offset and heave so that doesn't help us here. But,
# processed data objects have the heave attribute if heave data were
# recorded so we can use that.
if hasattr(Sv_38_depth, 'heave'):
    # heave data are available so we need to back that it out
    bottom_38_as_depth = bottom_38_as_depth_w_heave - Sv_38_depth.heave
    # heave is global, so if one channel has it, all channels will
    # so we don't have to check the 120.
    bottom_120_as_depth = bottom_120_as_depth_w_heave - Sv_120_depth.heave
else:
    # No heave data available which means no heave would have been
    # applied to the bottom detections so bottom_38_as_depth_w_heave
    # is depth without heave. Same for the 120 kHz.
    bottom_38_as_depth = bottom_38_as_depth_w_heave
    bottom_120_as_depth = bottom_120_as_depth_w_heave

# Set the color of our DEPTH lines to green
bottom_38_as_depth.color = [0, 1, 0]
bottom_120_as_depth.color = [0, 1, 0]


# Create matplotlib echograms and plot the data on a DEPTH grid
# Plot the bottom detections as range as a purple line
# Plot the bottom detections as depth without heave as a green line.
# We also plot the detected bottom line that includes heave as a yellow line
fig_38 = figure()
eg = echogram.Echogram(fig_38, Sv_38_depth, threshold=[-70, -34], cmap='viridis')
eg.axes.set_title("38 kHz on Depth grid")
eg.plot_line(bottom_38_as_range, linewidth=2)
eg.plot_line(bottom_38_as_depth, linewidth=2)
eg.plot_line(bottom_38_as_depth_w_heave, linewidth=2)

fig_120 = figure()
eg = echogram.Echogram(fig_120, Sv_120_depth, threshold=[-70, -34], cmap='viridis')
eg.axes.set_title("120 kHz on Depth grid")
eg.plot_line(bottom_120_as_range, linewidth=2)
eg.plot_line(bottom_120_as_depth, linewidth=2)
eg.plot_line(bottom_120_as_depth_w_heave, linewidth=2)


show()

